spring:
  application:
    name: book_service
  data:
    mongodb:
      uri: mongodb://localhost:27017/book_service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8082
  servlet:
    context-path: /book

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.book_service: DEBUG
