spring:
  application:
    name: book_service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book_service
#      uri: mongodb://localhost:27017/book_service
server:
  port: 8082
  servlet:
    context-path: /book

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.book_service: DEBUG

